### ISSUE TITLE
Closing Tag Typo in CSS Basics Section

### ISSUE THREAD

**Issue by richakat** [learn-co-curriculum/html-images-overview#8]
In the CodePen example, Line 11 opens a paragraph with the tag <p>. On line 13, there is another paragraph tag "<p>" that, I think should be a closed tag, </p>. It is followed by line 14 </body> and line 15 </html>.

**Comment by rrcobb** [comment]
It sounds like this is an issue with a different lesson. If this is still a problem, please open an issue on that lesson. Thanks!
